export const predbs = [
  {
    name: 'Estafa Maestra',
    country: 'MEX',
    countryLabel: 'México',
    author: 'Animal Político & Mexicanos Contra la Corrupción',
    size: 2,
    slug: 'estafa-maestra',
    last: '2019-10-01',
    flag: require('../static/flags/mexico.svg'),
    file: require('../static/csvs/estafa-maestra.csv')
  },
  {
    name: 'Empresas Fantasma de Veracruz',
    country: 'MEX',
    countryLabel: 'México',
    author: 'Animal Político',
    size: 1,
    blockEdit: true,
    slug: 'estafa-maestra',
    last: '2019-10-01',
    flag: require('../static/flags/mexico.svg'),
    file: require('../static/csvs/empresas-fantasma-ver.csv')
  },
  {
    name: 'Privilegios Fiscales Condonados (2007-2015)',
    country: 'MEX',
    countryLabel: 'México',
    blockEdit: true,
    author: 'Fundar',
    size: 4,
    slug: 'estafa-maestra',
    last: '2019-10-01',
    flag: require('../static/flags/mexico.svg'),
    file: require('../static/csvs/pf-7-15.csv')
  },
  {
    name: 'Privilegios Fiscales Cancelaciones (2007-2015)',
    country: 'MEX',
    countryLabel: 'México',
    blockEdit: true,
    author: 'Fundar',
    size: 20,
    slug: 'estafa-maestra',
    last: '2019-10-01',
    flag: require('../static/flags/mexico.svg'),
    file: require('../static/csvs/pf-cancelaciones-715.csv')
  },
  {
    name: 'SAT Definitivos',
    description: 'Empresas fantasma definitivas',
    country: 'MEX',
    blockEdit: true,
    countryLabel: 'México',
    author: 'SAT',
    size: 5,
    slug: 'sat-definitivos',
    last: '2019-09-30',
    flag: require('../static/flags/mexico.svg'),
    file: require('../static/csvs/sat-def.csv')
  },
  {
    name: 'SAT Presuntos',
    description: 'Empresas fantasma definitivas',
    country: 'MEX',
    blockEdit: true,
    countryLabel: 'México',
    author: 'SAT',
    size: 3,
    slug: 'sat-definitivos',
    last: '2019-09-30',
    flag: require('../static/flags/mexico.svg'),
    file: require('../static/csvs/sat-pre.csv')
  },
  {
    name: 'SAT Desvirtuados',
    description: 'Empresas fantasma definitivas',
    country: 'MEX',
    blockEdit: true,
    countryLabel: 'México',
    author: 'SAT',
    size: 3,
    slug: 'sat-Desvirtuados',
    last: '2019-09-30',
    flag: require('../static/flags/mexico.svg'),
    file: require('../static/csvs/sat-desvirtuados.csv')
  },
  {
    name: 'SAT Favorables',
    description: 'Empresas fantasma definitivas',
    country: 'MEX',
    blockEdit: true,
    countryLabel: 'México',
    author: 'SAT',
    size: 3,
    slug: 'sat-favorables',
    last: '2019-09-30',
    flag: require('../static/flags/mexico.svg'),
    file: require('../static/csvs/sat-favorables.csv')
  },
  {
    name: '1,000 empresas más grandes por ingresos en 2017 (total patrimonio)',
    description: 'Empresas fantasma definitivas',
    country: 'COL',
    blockEdit: true,
    countryLabel: 'Colombia',
    author: 'Superintendencia de Sociedades.',
    size: 3,
    slug: 'sat-favorables',
    last: '2019-09-30',
    flag: require('../static/flags/colombia.svg'),
    file: require('../static/csvs/col-patrimonio-2017.csv')
  }
]
